/*
		A basic implementation of the JDialog class.
*/
package cCard.View;
import java.awt.*;
import javax.swing.*;

import cCard.Controller.Main;
import cCard.Model.CCDB;

public class JDialogGenBill extends javax.swing.JDialog
{
    String billstring;
    private Card parentframe;
    private Main main = new Main();
	public JDialogGenBill(Card parent)
	{
		super(parent);
			this.parentframe=parent;
			
			
			// This code is automatically generated by Visual Cafe when you add
			// components to the visual environment. It instantiates and initializes
			// the components. To modify the code, only use code syntax that matches
			// what Visual Cafe can generate, or Visual Cafe may be unable to back
			// parses  your Java file into its visual envirenment. 
			//{{ INIT_CONTROLS 
			getContentPane().setLayout(null);
			setSize(405,367);
			setVisible(false);
			getContentPane().add(JScrollPane1);
			JScrollPane1.setBounds(24,24,358,240);
			JScrollPane1.getViewport().add(JTextField1);
			JTextField1.setBounds(0,0,355,237);
			JButton_OK.setText("OK");
			JButton_OK.setActionCommand("OK");
			getContentPane().add(JButton_OK);
			JButton_OK.setBounds(156,276,96,24);
	
			int selection = parentframe.getTable().getSelectionModel().getMinSelectionIndex();
			String num=(String)parentframe.getModel().getValueAt(selection, 1);
			billstring=CCDB.findAccountByNumber(Long.parseLong(num)).generateMonthlyBills();
			
			
			// generate the string for the monthly bill
			
			JTextField1.setText(billstring);
			//}}
		
			//{{REGISTER_LISTENERS
			SymAction lSymAction = new SymAction();
			JButton_OK.addActionListener(lSymAction);
			//}
			
	}

	/*public JDialogGenBill()
	{
		this((Frame)null);
	}
*/


	//{{DECLARE_CONTROLS
	javax.swing.JScrollPane JScrollPane1 = new javax.swing.JScrollPane();
	javax.swing.JTextArea JTextField1 = new javax.swing.JTextArea();
	javax.swing.JButton JButton_OK = new javax.swing.JButton();
	//}}


	class SymAction implements java.awt.event.ActionListener
	{
		public void actionPerformed(java.awt.event.ActionEvent event)
		{
			Object object = event.getSource();
			if (object == JButton_OK)
				JButtonOK_actionPerformed(event);
		}
	}

	void JButtonOK_actionPerformed(java.awt.event.ActionEvent event)
	{
		dispose();
			 
	}
}
